### PR TITLE
Update F-keys in abby-left-hand-modifiers.py

### PR DESCRIPTION
**Pull request by phuertay**
F-keys weren't working as described in Abby's left hand modifiers documentation (RAO + binary number). Changed to follow

### CODE REVIEW

**Comment by aerickt** [comment]
hmm, I used my own copy of the dictionary when I added it to this plugin, and I guess I forgot I changed the function keys.

However, looking at the original, this is how Emily's modifiers works, and I think there's a benefit to having some consistency between the two systems.

I'll get around the updating the docs soon to mention this change.

**Comment by phuertay** [comment]
Ah, I see. That makes sense. Should all numbers in Abby's modifiers follow the same convention then?

**Comment by aerickt** [comment]
Sure, good idea. Should be fixed now. All that's left is to update the documentation.

**Comment by phuertay** [comment]
Maybe also for numpad keys? (lines 81 to 90)?

**Comment by aerickt** [comment]
Sure. I'll take a look on the weekend.

**Pull request closed without merging**
